# Generated by Django 5.2.5 on 2025-09-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
